import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
const base=process.env.MPX_PROJECTS;if(!base)throw Error('MPX_PROJECTS is required');
const repo=process.cwd(), slash=s=>s.split(path.sep).join('/');
const roots=[['mpx',['content','scripts','packages/runtime-hooks/src','runtimes/pi/extensions']],['mpx-claude-code',['plugins/mp/skills','plugins/gh/skills','local/skills','plugins/mp/agents','plugins/gh/agents','instructions','rules','rules-per-project','plugins/mp/scripts','plugins/mp/hooks','plugins/mp/templates']],['mpx-pi',['extensions','scripts','prompts']]];
const skip=new Set(['node_modules','dist','.git','deprecated','cache','caches','archive']);
const excluded=n=>/^nul$/i.test(n)||/^(auth|credentials|settings)\.json$/i.test(n)||/\.bak$/i.test(n)||/(logs|transcripts)/i.test(n);
const files=[];function walk(a){let s;try{s=fs.lstatSync(a)}catch{return}if(s.isSymbolicLink()){files.push({a,link:fs.readlinkSync(a)});return}if(s.isDirectory()){for(const e of fs.readdirSync(a,{withFileTypes:true}))if(!skip.has(e.name)&&!excluded(e.name))walk(path.join(a,e.name));}else if(s.isFile()&&!excluded(path.basename(a)))files.push({a})}
for(const [p,rs] of roots)for(const r of rs)walk(path.join(base,p,r));
const rel=a=>slash(path.relative(base,a)), source=a=>`$MPX_PROJECTS/${rel(a)}`;
const norm=s=>s.toLowerCase().replace(/^(mp|gh|kf|mpx)-/,'');
const originals=files.filter(f=>rel(f.a).startsWith('mpx-claude-code/'));
function counterpart(a){const n=norm(path.basename(a)),d=norm(path.basename(path.dirname(a)));const h=originals.filter(f=>norm(path.basename(f.a))===n&&(!rel(a).includes('/skills/')||norm(path.basename(path.dirname(f.a)))===d));return h.length?h.map(f=>`UNVERIFIED $MPX_PROJECTS/${rel(f.a)}`).join('; '):'none identified'}
function deps(f){if(f.link)return'symlink target (not read); closure unverified';let t;try{t=fs.readFileSync(f.a,'utf8')}catch{return'unreadable; closure unverified'}const o=new Set;for(const m of t.matchAll(/(?:!?)\[[^\]]*\]\(([^)#]+)|(?:from|require\s*\(|import\s*\()["']([^"']+)|\b(mpx-[A-Za-z0-9._/@-]+)/g))o.add(m[1]||m[2]||m[3]);return(o.size?[...o].join(', '):'none lexically found')+'; closure unverified'}
const core=new Set(['execute','review','check-fix','commit','commit-push','commit-push-pr','ship','design-init','design-brief','mockup','design-refine','grill','handoff','issue','pr','ci']);
const rows=files.map(f=>{const r=rel(f.a),isSkill=path.basename(f.a)==='SKILL.md'&&r.startsWith('mpx/content/skills/');const n=isSkill?path.basename(path.dirname(f.a)).toLowerCase():path.basename(f.a,path.extname(f.a)).toLowerCase();return[r,(r.startsWith('mpx/')?'':'original-only: ')+source(f.a)+(f.link?` (symlink; target inspection pending)`:''),counterpart(f.a),'UNVERIFIED',deps(f),isSkill&&core.has(n)?'daily-core':'adapt-later','required rewrite pending adaptation review','enumerated working-tree file; adaptation/closure unverified','retention pending adaptation; no retirement approved']});
for(const n of ['pi-mcp-adapter','pi-web-access','@juicesharp/rpiv-ask-user-question','@tintinweb/pi-subagents','Orca status','Orca prefill','Orca titlebar','Orca machine-root shim'])rows.push([n,'installed account state; target inspection pending','not yet resolved','UNVERIFIED','target/loading/compatibility unverified','adapt-later','required rewrite pending adaptation review','target/loading/compatibility unverified','retention pending adaptation; no retirement approved']);
const old=fs.existsSync('migration/INVENTORY.md')?fs.readFileSync('migration/INVENTORY.md','utf8'):'';const review=old.includes('# Reviewed adaptation evidence')?old.slice(old.indexOf('# Reviewed adaptation evidence')):'\n# Reviewed adaptation evidence\n';
let out='# Migration-local inventory\n\nThis is a migration-local inventory, not a runtime manifest. Byte-preserving source status is read-only; source HEAD and git status counts are recorded (never copies from HEAD); no whole repos copied. Dependency entries are lexical leads only; closure is unverified. This deterministic enumeration is not behavioral reduction.\n\nRoots enumerated exactly: '+roots.flatMap(([p,rs])=>rs.map(r=>`$MPX_PROJECTS/${p}/${r}`)).join(', ')+'.\n\n| identity | current source | original counterpart | behavioral differences | dependencies | disposition | required rewrite | acceptance evidence | user approval |\n|---|---|---|---|---|---|---|---|---|\n'+rows.map(r=>`| ${r.map(x=>String(x).replaceAll('|','\\|')).join(' | ')} |`).join('\n')+'\n\n';
const c={};for(const r of rows)c[r[5]]=(c[r[5]]||0)+1;out+=`Category counts: ${Object.entries(c).map(([k,v])=>`${k}=${v}`).join(', ')}.\n`;for(const [p] of roots){let h='unavailable',s='unavailable';try{h=execFileSync('git',['rev-parse','HEAD'],{cwd:path.join(base,p),encoding:'utf8'}).trim();s=execFileSync('git',['status','--short'],{cwd:path.join(base,p),encoding:'utf8'}).trim().split('\n').filter(Boolean).length}catch{}out+=`${p} source HEAD: ${h}; git status entries: ${s}.\n`}fs.writeFileSync('migration/INVENTORY.md',out+review);console.log(`enumerated ${files.length} files; ${JSON.stringify(c)}`);
