import { lstat, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { ExecutionError } from "./index.js";
const SHA=/^[a-f0-9]{64}$/u,MAX=64*1024;
export interface StoredF2Evidence {readonly schemaVersion:1;readonly planKey:string;readonly runtimeToolInventorySha256:string;readonly proof:{readonly verdict:"pass"|"fail";readonly attestationSha256:string}}
export class F2EvidenceStore{
 constructor(readonly root:string){if(!path.isAbsolute(root))throw new ExecutionError("EVIDENCE_PATH_INVALID","Evidence root must be absolute.")}
 async put(input:Omit<StoredF2Evidence,"schemaVersion">):Promise<void>{if(!SHA.test(input.planKey)||!SHA.test(input.runtimeToolInventorySha256)||!SHA.test(input.proof.attestationSha256)||!['pass','fail'].includes(input.proof.verdict))throw new ExecutionError("EVIDENCE_INVALID","Evidence is malformed.");await mkdir(this.root,{recursive:true});const stat=await lstat(this.root);if(stat.isSymbolicLink()||!stat.isDirectory())throw new ExecutionError("EVIDENCE_PATH_INVALID","Evidence root is unsafe.");const body=`${JSON.stringify({schemaVersion:1,...input})}\n`;if(Buffer.byteLength(body)>MAX)throw new ExecutionError("EVIDENCE_INVALID","Evidence exceeds storage bounds.");const temporary=path.join(this.root,`.${input.planKey}.${randomUUID()}.tmp`),target=path.join(this.root,`${input.planKey}.json`);try{await writeFile(temporary,body,{flag:"wx",mode:0o600});await rename(temporary,target)}finally{await rm(temporary,{force:true})}}
 async get(planKey:string,currentInventorySha256:string):Promise<{valid:true;evidence:StoredF2Evidence}|{valid:false;reason:"NOT_FOUND"|"RUNTIME_TOOL_INVENTORY_DRIFT"|"EVIDENCE_INVALID"}>{if(!SHA.test(planKey)||!SHA.test(currentInventorySha256))throw new ExecutionError("EVIDENCE_INVALID","Evidence lookup hashes are invalid.");const file=path.join(this.root,`${planKey}.json`);const raw=await readFile(file).catch(error=>{if((error as NodeJS.ErrnoException).code==='ENOENT')return undefined;throw error});if(raw===undefined)return {valid:false,reason:"NOT_FOUND"};if(raw.byteLength>MAX)return {valid:false,reason:"EVIDENCE_INVALID"};try{const item=JSON.parse(raw.toString('utf8')) as StoredF2Evidence;if(item.schemaVersion!==1||item.planKey!==planKey||!SHA.test(item.runtimeToolInventorySha256)||!item.proof||!SHA.test(item.proof.attestationSha256)||!['pass','fail'].includes(item.proof.verdict)||Object.keys(item).sort().join(',')!=="planKey,proof,runtimeToolInventorySha256,schemaVersion")return {valid:false,reason:"EVIDENCE_INVALID"};if(item.runtimeToolInventorySha256!==currentInventorySha256)return {valid:false,reason:"RUNTIME_TOOL_INVENTORY_DRIFT"};return {valid:true,evidence:Object.freeze(item)}}catch{return {valid:false,reason:"EVIDENCE_INVALID"}}}
}
