import { randomUUID } from "node:crypto";
import { chmod, lstat, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { ExecutionError } from "./index.js";
const SHA=/^[a-f0-9]{64}$/u;
const NAME=/^[a-z0-9][a-z0-9-]{0,62}$/u;
export interface SandboxResumeStateV1 {readonly sandboxName:string;readonly appNamespace:string;readonly launchKey:string;readonly planKey:string;readonly runtimeInventorySha256:string;readonly workspaceIdentitySha256:string;readonly branchIdentitySha256:string;readonly attestationSha256:string}
export interface SandboxResumeVerification {readonly workerSha256:string;readonly projectionSha256:string;readonly mountsSha256:string;readonly networkSha256:string;readonly portsSha256:string;readonly accountEnrollmentSha256:string;readonly identitySha256:string}
export interface SbxListEntryV1 extends SandboxResumeStateV1,SandboxResumeVerification {readonly status:"running"|"stopped"}
const stateKeys=["sandboxName","appNamespace","launchKey","planKey","runtimeInventorySha256","workspaceIdentitySha256","branchIdentitySha256","attestationSha256"] as const;
const verificationKeys=["workerSha256","projectionSha256","mountsSha256","networkSha256","portsSha256","accountEnrollmentSha256","identitySha256"] as const;
function validState(value:Record<string,unknown>):boolean{return NAME.test(String(value.sandboxName))&&NAME.test(String(value.appNamespace))&&stateKeys.slice(2).every(key=>SHA.test(String(value[key])))}
export function createSandboxResumeStateV1(input:SandboxResumeStateV1):SandboxResumeStateV1{const copy=Object.fromEntries(stateKeys.map(key=>[key,input[key]])) as unknown as SandboxResumeStateV1;if(!validState(copy as unknown as Record<string,unknown>))throw new ExecutionError("SANDBOX_RESUME_INVALID","Sandbox resume authority is malformed.");return Object.freeze(copy)}
export function parseSbxListV1(text:string):readonly SbxListEntryV1[]{if(Buffer.byteLength(text)>65_536)throw new ExecutionError("SBX_LIST_INVALID","sbx ls output exceeds bounds.");let raw:unknown;try{raw=JSON.parse(text)}catch{throw new ExecutionError("SBX_LIST_INVALID","sbx ls output is invalid JSON.")}if(!Array.isArray(raw)||raw.length>256)throw new ExecutionError("SBX_LIST_INVALID","sbx ls output must be a bounded array.");const exact=[...stateKeys,"status",...verificationKeys].sort().join(",");return Object.freeze(raw.map(item=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new ExecutionError("SBX_LIST_INVALID","sbx ls entry is invalid.");const value=item as Record<string,unknown>;if(Object.keys(value).sort().join(",")!==exact||!validState(value)||!["running","stopped"].includes(String(value.status))||!verificationKeys.every(key=>SHA.test(String(value[key]))))throw new ExecutionError("SBX_LIST_INVALID","sbx ls entry fields are not exact.");return Object.freeze({...value}) as unknown as SbxListEntryV1}))}
export interface ResumeDecision {readonly action:"attach"|"recreate";readonly reasons:readonly string[]}
export function decideSandboxResume(state:SandboxResumeStateV1,observed:SbxListEntryV1|undefined,expected:SandboxResumeVerification):ResumeDecision{createSandboxResumeStateV1(state);const reasons:string[]=[];if(!observed)reasons.push("sandboxName: absent");else{if(observed.status!=="running")reasons.push("status: not running");for(const key of stateKeys)if(observed[key]!==state[key])reasons.push(`${key}: mismatch`);for(const key of verificationKeys)if(observed[key]!==expected[key])reasons.push(`${key}: mismatch`)}return Object.freeze({action:reasons.length?"recreate":"attach",reasons:Object.freeze(reasons)})}
export interface SandboxRuntimeHandle {readonly name:string;readonly appNamespace:string;send(line:string,signal?:AbortSignal):Promise<string>;writeInput?(requestId:string,payload:string,signal?:AbortSignal):Promise<void>;readOutput(requestId:string):Promise<string>;publishedPort(assignedPort:number):{readonly host:"127.0.0.1";readonly port:number}}
export interface SandboxLifecycleAttachment {readonly name:string}
export interface SandboxLifecycleBackend {list(signal?:AbortSignal):Promise<readonly SbxListEntryV1[]>;attach(name:string,signal?:AbortSignal):Promise<SandboxLifecycleAttachment>;destroy(name:string):Promise<void>;create(state:SandboxResumeStateV1,signal?:AbortSignal):Promise<SandboxLifecycleAttachment>}
export class SandboxLifecycle {constructor(readonly backend:SandboxLifecycleBackend){}async resumeOrRecreate(stateInput:SandboxResumeStateV1,verification:SandboxResumeVerification,signal?:AbortSignal):Promise<SandboxLifecycleAttachment>{const state=createSandboxResumeStateV1(stateInput);if(signal?.aborted)throw Object.assign(new Error("Sandbox resume was cancelled."),{code:"ABORT_ERR"});const entries=await this.backend.list(signal);const matching=entries.find(entry=>entry.sandboxName===state.sandboxName);const decision=decideSandboxResume(state,matching,verification);if(decision.action==="attach")return this.backend.attach(state.sandboxName,signal);if(matching)await this.backend.destroy(state.sandboxName);try{return await this.backend.create(state,signal)}catch(error){await this.backend.destroy(state.sandboxName).catch(()=>{});throw error}}}
export class SandboxResumeStore {constructor(readonly root:string){if(!path.isAbsolute(root))throw new ExecutionError("SANDBOX_RESUME_PATH_INVALID","Sandbox resume root must be absolute.")}private file(name:string){if(!NAME.test(name))throw new ExecutionError("SANDBOX_RESUME_INVALID","Sandbox name is invalid.");return path.join(this.root,`${name}.json`)}async save(input:SandboxResumeStateV1):Promise<void>{const state=createSandboxResumeStateV1(input);await mkdir(this.root,{recursive:true,mode:0o700});const stat=await lstat(this.root);if(stat.isSymbolicLink()||!stat.isDirectory())throw new ExecutionError("SANDBOX_RESUME_PATH_INVALID","Sandbox resume root is unsafe.");const target=this.file(state.sandboxName),temporary=path.join(this.root,`.${state.sandboxName}.${randomUUID()}.tmp`);try{await writeFile(temporary,`${JSON.stringify(state)}\n`,{encoding:"utf8",flag:"wx",mode:0o600});await chmod(temporary,0o600).catch(()=>{});await rename(temporary,target)}finally{await rm(temporary,{force:true})}}async load(name:string):Promise<SandboxResumeStateV1|undefined>{const raw=await readFile(this.file(name)).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error});if(!raw)return undefined;if(raw.byteLength>16_384)throw new ExecutionError("SANDBOX_RESUME_INVALID","Sandbox resume state exceeds bounds.");let value:unknown;try{value=JSON.parse(raw.toString("utf8"))}catch{throw new ExecutionError("SANDBOX_RESUME_INVALID","Sandbox resume state is invalid JSON.")}if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).sort().join(",")!==[...stateKeys].sort().join(","))throw new ExecutionError("SANDBOX_RESUME_INVALID","Sandbox resume state fields are not exact.");return createSandboxResumeStateV1(value as SandboxResumeStateV1)}}
/** Session-neutral API gate: callers provide immutable launch-derived hashes, never session records. */
export function gateLaunchSandboxResume(input:{executor:"docker"|"host";launchKey:string;state:SandboxResumeStateV1;observed:SbxListEntryV1|undefined;verification:SandboxResumeVerification}):ResumeDecision{if(input.executor!=="docker")return Object.freeze({action:"recreate",reasons:Object.freeze(["executor: docker required"])});if(input.launchKey!==input.state.launchKey)return Object.freeze({action:"recreate",reasons:Object.freeze(["launchKey: mismatch"])});return decideSandboxResume(input.state,input.observed,input.verification)}
