import { execFile as execFileCallback } from "node:child_process";
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { afterEach, describe, expect, it } from "vitest";
import { inventoryCanonical, resolveManifest, createRuntimeSkillArtifact } from "@mpx/skills";
import { buildClaudePlugin, createClaudeInvocationPlan, renderClaudeStatusLine, diagnoseLegacyNamespaceConflicts } from "./index.js";
import { renderClaudePortSegment } from "@mpx/status";
import { createRuntimeContextV1, createRuntimeSkillArtifactReferenceV4, publishRuntimeArtifact } from "@mpx/runtime-contracts";

const execFile = promisify(execFileCallback);
const roots:string[]=[]; afterEach(async()=>Promise.all(roots.splice(0).map(x=>rm(x,{recursive:true,force:true}))));
const statusSnapshot={schemaVersion:1 as const,project:{id:"sample/app",cwd:"C:/repo"},worktree:{id:"wt-1",path:"C:/repo",role:"main" as const,branch:"main"},portResolution:"valid" as const,services:[{id:"api",mode:"managed" as const,scope:"checkout" as const,protocol:"http" as const,port:4101,listening:true,conflict:"none" as const,pid:7},{id:"web",mode:"fixed-shared" as const,scope:"project" as const,protocol:"https" as const,port:4443,listening:false,conflict:"external" as const,pid:null}],diagnostics:[]};
const launchBanner="[mpx claude/docker 123456789abc]";
const projectionReference=createRuntimeSkillArtifactReferenceV4({runtime:"claude",manifestKey:"a".repeat(64),artifactKey:"b".repeat(64),fileMapHash:"c".repeat(64)});
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),"claude-runtime-"));roots.push(root);const canonical=path.join(root,"skills"),agents=path.join(root,"agents");await mkdir(canonical);await mkdir(agents);for(const [name,exposure] of Object.entries({full:"full",named:"name-only",explicit:"explicit-only",off:"off"})){await mkdir(path.join(canonical,name));await writeFile(path.join(canonical,name,"SKILL.md"),`---\nname: ${name}\ndescription: secret ${name} description\ntriggers: trigger ${name}\nmetadata:\n  mpx:\n    skillPacks: [core]\n    defaultExposure: ${exposure}\n---\nBODY ${name}\n`);}await writeFile(path.join(agents,"mpx-checker.md"),"---\nname: mpx-checker\ndescription: Check things\n---\nAGENT BODY\n");const catalog=await inventoryCanonical(canonical);const manifest=resolveManifest(catalog,{repositoryId:"repo",contentScope:"personal",identity:"id",skillPolicy:"p",skillPolicyConfig:{skillExposure:{default:"full",skills:{full:"full",named:"name-only",explicit:"explicit-only",off:"off"}}},enabledPacks:["core"]});const artifact=createRuntimeSkillArtifact(manifest,catalog,{runtime:"claude"});const runtimeContext=createRuntimeContextV1({launchKey:"a".repeat(64),launchDescriptor:{reference:"launch.json",digest:"b".repeat(64)},manifestKey:manifest.manifestKey,runtimeArtifact:artifact.reference,binding:manifest.binding});return {root,canonical,agents,catalog,manifest,artifact,statusSnapshot,launchBanner,runtimeContext};}
async function tree(root:string){const out:Record<string,string>={};async function walk(d:string){for(const e of await readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())await walk(p);else out[path.relative(root,p).replaceAll("\\","/")]=await readFile(p,"utf8");}}await walk(root);return out;}
async function linkDirectory(target:string,link:string){await symlink(target,link,process.platform==="win32"?"junction":"dir");}
function changedArtifact<T>(value:T, change:(copy:any)=>void):T { const copy=structuredClone(value);change(copy);return copy; }
async function expectArtifactRejectedWithoutWrites(f:Awaited<ReturnType<typeof fixture>>,artifact:any,name:string){const outputRoot=path.join(f.root,name);await expect(buildClaudePlugin({...f,artifact,outputRoot})).rejects.toThrow(/RUNTIME_ARTIFACT_TAMPERED/);await expect(lstat(outputRoot)).rejects.toMatchObject({code:"ENOENT"});}
describe("Claude projection",()=>{
 it("rejects a tampered artifact entry before filesystem side effects",async()=>{const f=await fixture();await expectArtifactRejectedWithoutWrites(f,changedArtifact(f.artifact,a=>a.entries[0].metadataHash="0".repeat(64)),"tampered-entry");});
 it("rejects tampered artifact permissions before filesystem side effects",async()=>{const f=await fixture();await expectArtifactRejectedWithoutWrites(f,changedArtifact(f.artifact,a=>a.entries[0].permissions.humanInvocation=false),"tampered-permission");});
 it("rejects tampered artifact exposure before filesystem side effects",async()=>{const f=await fixture();await expectArtifactRejectedWithoutWrites(f,changedArtifact(f.artifact,a=>a.entries[0].exposure="off"),"tampered-exposure");});
 it("rejects an extra artifact entry before filesystem side effects",async()=>{const f=await fixture();await expectArtifactRejectedWithoutWrites(f,changedArtifact(f.artifact,a=>a.entries.push({...a.entries[0],identity:"extra"})),"extra-entry");});
 it("rejects a missing artifact entry before filesystem side effects",async()=>{const f=await fixture();await expectArtifactRejectedWithoutWrites(f,changedArtifact(f.artifact,a=>a.entries.pop()),"missing-entry");});
 it("projects the four exposure states with exact mpx namespace and non-leaking discovery",async()=>{const f=await fixture(),out=path.join(f.root,"out");await buildClaudePlugin({...f,outputRoot:out});const files=await tree(out);expect(Object.keys(files).filter(x=>x.startsWith("skills/"))).toEqual(["skills/explicit/SKILL.md","skills/full/SKILL.md","skills/named/SKILL.md"]);expect(files[".claude-plugin/plugin.json"]).toContain('"name": "mpx"');expect(files["skills/full/SKILL.md"]).toContain("secret full description");expect(files["skills/named/SKILL.md"]).not.toContain("secret named");expect(files["skills/explicit/SKILL.md"]).toContain("disable-model-invocation: true");expect(files["skills/explicit/SKILL.md"]).toContain("BODY explicit");});
 it("creates deterministic self-contained files and changes projection for a different artifact key",async()=>{const f=await fixture(),a=path.join(f.root,"a"),b=path.join(f.root,"b");await buildClaudePlugin({...f,outputRoot:a});await buildClaudePlugin({...f,outputRoot:b});expect(await tree(a)).toEqual(await tree(b));for(const rel of Object.keys(await tree(a)))expect((await lstat(path.join(a,rel))).isSymbolicLink()).toBe(false);const altered={...f.artifact,reference:{...f.artifact.reference,artifactKey:"different"}};await expect(buildClaudePlugin({...f,artifact:altered,outputRoot:path.join(f.root,"c")})).rejects.toThrow(/STALE_ARTIFACT/);});
 it("generates canonical agents, hooks, local status renderer, and settings",async()=>{const f=await fixture(),out=path.join(f.root,"out");await buildClaudePlugin({...f,outputRoot:out});const files=await tree(out);expect(files["agents/mpx-checker.md"]).toContain("name: mpx-checker");expect(JSON.parse(files["hooks/hooks.json"]!)).toHaveProperty("hooks.PreToolUse.0.matcher","Skill|Agent|Task|Bash");expect(JSON.parse(files["settings.json"]!).statusLine.command).toBe('node "${CLAUDE_PLUGIN_ROOT}/status/status-line.mjs"');expect(files["status/status-snapshot.json"]).toBe(`${JSON.stringify(statusSnapshot,null,2)}\n`);expect((await execFile(process.execPath,[path.join(out,"status","status-line.mjs")],{env:{...process.env,MPX_STATUS_SNAPSHOT_FILE:path.join(out,"status","status-snapshot.json")}})).stdout).toBe(renderClaudeStatusLine(statusSnapshot,{launchBanner}));expect(Object.keys(files).some(x=>x.includes("provider"))).toBe(false);});
 it("executes every earliest hook checkpoint against the full published projection",async()=>{const f=await fixture(),staging=path.join(f.root,"staging"),artifacts=path.join(f.root,"artifacts");await buildClaudePlugin({...f,outputRoot:staging});const published=await publishRuntimeArtifact({sourceRoot:staging,artifactsRoot:artifacts,runtime:"claude",manifestKey:f.manifest.manifestKey});const hooks=JSON.parse((await tree(published.directory))["hooks/hooks.json"]!).hooks;expect(Object.keys(hooks).sort()).toEqual(["PreToolUse","SessionStart","UserPromptSubmit"]);await writeFile(path.join(published.directory,"settings.json"),"tampered\n");for(const event of Object.values(hooks) as any[]){for(const group of event){for(const hook of group.hooks){const command=hook.command.replace("${CLAUDE_PLUGIN_ROOT}",published.directory);expect(command.replaceAll("\\","/")).toContain(`${published.directory.replaceAll("\\","/")}/hooks/runtime-guard.mjs`);await expect(execFile(process.execPath,[path.join(published.directory,"hooks","runtime-guard.mjs")],{env:{...process.env,MPX_RUNTIME_CONTEXT:JSON.stringify(f.runtimeContext),MPX_RUNTIME_PROJECTION_REFERENCE:JSON.stringify(published.reference)}})).rejects.toMatchObject({code:2,stderr:expect.stringContaining("ARTIFACT_FILE_MAP_CHANGED")});}}}});
 it("reads current validated status from the private launch-bound path on every status use",async()=>{const f=await fixture(),out=path.join(f.root,"out"),snapshotFile=path.join(f.root,"live-status.json");await buildClaudePlugin({...f,outputRoot:out});await writeFile(snapshotFile,JSON.stringify(statusSnapshot));const run=()=>execFile(process.execPath,[path.join(out,"status","status-line.mjs")],{env:{...process.env,MPX_STATUS_SNAPSHOT_FILE:snapshotFile}});expect((await run()).stdout).toContain("api:4101*");await writeFile(snapshotFile,JSON.stringify({...statusSnapshot,portResolution:"stale",services:[]}));expect((await run()).stdout).toBe(`${launchBanner} | ports stale`);});
 it("rejects symlinked canonical agent and references roots",async()=>{const f=await fixture();const linkedAgents=path.join(f.root,"linked-agents");await linkDirectory(f.agents,linkedAgents);await expect(buildClaudePlugin({...f,agents:linkedAgents,outputRoot:path.join(f.root,"out-linked")})).rejects.toThrow(/AGENT_ROOT/u);await rm(linkedAgents,{recursive:true,force:true});await mkdir(path.join(f.agents,"references"));const safeReference=path.join(f.root,"safe-references");await mkdir(safeReference);await writeFile(path.join(safeReference,"guide.md"),"guide\n");await rm(path.join(f.agents,"references"),{recursive:true,force:true});await linkDirectory(safeReference,path.join(f.agents,"references"));await expect(buildClaudePlugin({...f,outputRoot:path.join(f.root,"out-references")})).rejects.toThrow(/REFERENCE|AGENT_ROOT/u);});
 it("never writes a private account root into public projection references or generated plugin bytes",async()=>{const f=await fixture(),out=path.join(f.root,"out"),accountRoot="C:/native/claude/private-account";const projection=await buildClaudePlugin({...f,outputRoot:out});expect(JSON.stringify({artifactKey:projection.artifactKey,files:projection.files})).not.toContain(accountRoot);expect(JSON.stringify(await tree(out))).not.toContain(accountRoot);});
});
it("renders the validated shared status segment with the compact launch banner",()=>{expect(renderClaudeStatusLine(statusSnapshot,{launchBanner})).toBe(`${launchBanner} | ${renderClaudePortSegment(statusSnapshot)}`);});
it("preserves argv-only launch context and fails closed on legacy namespace conflict",()=>{const plan=createClaudeInvocationPlan({executable:"C:/tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/_MP_work/repo",accountRoot:"C:/native/claude/account-a",runtimeContext:{launchKey:"k"},projectionReference,environment:{MPX_WORK:"C:/_MP_work",MPX_PROJECTS:"C:/_MP_projects"}});expect(plan).toMatchObject({executable:"C:/tools/claude.exe",args:["--plugin-dir","C:/artifact"]});expect(plan.env.MPX_RUNTIME_CONTEXT).toBe('{"launchKey":"k"}');expect(()=>diagnoseLegacyNamespaceConflicts(["mp","mp-gh"])).toThrow(/LEGACY_NAMESPACE_CONFLICT/);});
it("binds the privately selected Claude account root only in the child environment",()=>{const accountRoot="C:/native/claude/account-a";const plan=createClaudeInvocationPlan({executable:"C:/tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/repo",accountRoot,runtimeContext:{launchKey:"k"},projectionReference,environment:{CLAUDE_CONFIG_DIR:accountRoot}});expect(plan).toEqual({executable:"C:/tools/claude.exe",args:["--plugin-dir","C:/artifact"],env:{CLAUDE_CONFIG_DIR:accountRoot,MPX_RUNTIME_CONTEXT:'{"launchKey":"k"}',MPX_RUNTIME_PROJECTION_REFERENCE:expect.any(String)}});});
it("binds the live status snapshot path privately in the Claude child environment",()=>{const plan=createClaudeInvocationPlan({executable:"C:/tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/repo",accountRoot:"C:/native/claude/account-a",runtimeContext:{launchKey:"k"},projectionReference,statusSnapshotPath:"C:/private/status/current.json",environment:{}});expect(plan.env.MPX_STATUS_SNAPSHOT_FILE).toBe("C:/private/status/current.json");expect(plan.args.join(" ")).not.toContain("current.json");});
it("rejects a missing privately selected Claude account root",()=>{expect(()=>createClaudeInvocationPlan({executable:"C:/tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/repo",accountRoot:undefined as unknown as string,runtimeContext:{launchKey:"k"},projectionReference,environment:{}})).toThrow(/NATIVE_ROOT_REQUIRED/);});
it("rejects a relative privately selected Claude account root",()=>{expect(()=>createClaudeInvocationPlan({executable:"C:/tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/repo",accountRoot:"native/claude/account-a",runtimeContext:{launchKey:"k"},projectionReference,environment:{}})).toThrow(/NATIVE_ROOT_NOT_ABSOLUTE/);});
it("rejects an inherited Claude config root that mismatches the private selection",()=>{expect(()=>createClaudeInvocationPlan({executable:"C:/tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/repo",accountRoot:"C:/native/claude/account-a",runtimeContext:{launchKey:"k"},projectionReference,environment:{CLAUDE_CONFIG_DIR:"C:/native/claude/account-b"}})).toThrow(/NATIVE_ROOT_MISMATCH/);});
it("rejects a relative Claude executable without changing argv construction",()=>{expect(()=>createClaudeInvocationPlan({executable:"tools/claude.exe",pluginDirectory:"C:/artifact",repositoryRoot:"C:/repo",accountRoot:"C:/native/claude/account-a",runtimeContext:{launchKey:"k"},projectionReference,environment:{}})).toThrow(/UNTRUSTED_PATH/);});
