import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  checkActiveContentProjection,
  loadActiveContentProjection,
  readActiveContentEntry,
} from '../../src/index.js';

const sha256 = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), 'mpx-active-content-'));
  const skill = Buffer.from('skill bytes\r\n', 'utf8');
  const agent = Buffer.from('agent bytes\n', 'utf8');
  await mkdir(path.join(root, 'skills', 'alpha'), { recursive: true });
  await mkdir(path.join(root, 'agents'), { recursive: true });
  await writeFile(path.join(root, 'skills', 'alpha', 'SKILL.md'), skill);
  await writeFile(path.join(root, 'agents', 'Explore.md'), agent);
  const manifest = {
    schemaVersion: 1,
    compilerVersion: '1.0.0',
    runtime: 'claude',
    profileSchemaVersion: 1,
    binding: { projectId: null, repositoryId: 'repo', contentScope: 'test' },
    manifestKey: 'manifest-key',
    manifestEnvelope: { path: 'active-content.json', includedInFileMap: false },
    skills: [
      {
        identity: 'alpha',
        exposure: 'full',
        canonicalDescription: 'Alpha.',
        effectiveDescription: 'Alpha.',
        sourcePath: 'alpha/SKILL.md',
        generatedPath: 'skills/alpha/SKILL.md',
        generatedSha256: sha256(skill),
        bodyByteOffset: 0,
        omittedOptionalFeatures: [],
      },
    ],
    agents: [
      {
        canonicalIdentity: 'mpx-explorer',
        projectedIdentity: 'Explore',
        semanticModel: 'standard',
        concreteModel: 'sonnet',
        thinking: 'medium',
        capabilities: ['read'],
        tools: ['Read'],
        nesting: { canonical: [], projected: [], requiredTools: [] },
        outputSchema: 'text',
        sourcePath: 'mpx-explorer.md',
        sourceSha256: 'a'.repeat(64),
        sourceByteCount: 10,
        generatedPath: 'agents/Explore.md',
        generatedSha256: sha256(agent),
        generatedByteCount: agent.byteLength,
      },
    ],
    files: [
      { relativePath: 'agents/Explore.md', sha256: sha256(agent), byteCount: agent.byteLength },
      {
        relativePath: 'skills/alpha/SKILL.md',
        sha256: sha256(skill),
        byteCount: skill.byteLength,
      },
    ],
  };
  const manifestPath = path.join(root, 'active-content.json');
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  return { root, manifestPath, skill, agent, manifest };
}

describe('persisted active content', () => {
  it('loads only an exact root-to-manifest binding and rejects unknown manifest fields', async () => {
    const value = await fixture();
    await expect(
      loadActiveContentProjection({ root: value.root, manifestPath: value.manifestPath }),
    ).resolves.toMatchObject({ root: value.root, manifestPath: value.manifestPath });

    await writeFile(value.manifestPath, JSON.stringify({ ...value.manifest, unexpected: true }));
    await expect(
      loadActiveContentProjection({ root: value.root, manifestPath: value.manifestPath }),
    ).rejects.toMatchObject({ code: 'ACTIVE_CONTENT_MANIFEST_INVALID' });
  });

  it('returns the exact verified generated bytes for skill and either agent identity', async () => {
    const value = await fixture();
    const active = await loadActiveContentProjection({
      root: value.root,
      manifestPath: value.manifestPath,
    });

    await expect(readActiveContentEntry(active, 'skill', 'alpha')).resolves.toEqual(value.skill);
    await expect(readActiveContentEntry(active, 'agent', 'mpx-explorer')).resolves.toEqual(
      value.agent,
    );
    await expect(readActiveContentEntry(active, 'agent', 'Explore')).resolves.toEqual(value.agent);
  });

  it('rejects mutation before returning generated bytes', async () => {
    const value = await fixture();
    const active = await loadActiveContentProjection({
      root: value.root,
      manifestPath: value.manifestPath,
    });
    await writeFile(path.join(value.root, 'skills', 'alpha', 'SKILL.md'), 'mutated');

    await expect(readActiveContentEntry(active, 'skill', 'alpha')).rejects.toMatchObject({
      code: 'ACTIVE_CONTENT_TAMPERED',
    });
  });

  it('checks every represented compiler file while excluding the manifest self-hash', async () => {
    const value = await fixture();
    const active = await loadActiveContentProjection({
      root: value.root,
      manifestPath: value.manifestPath,
    });
    await expect(checkActiveContentProjection(active)).resolves.toEqual({
      checkedFiles: 2,
      clean: true,
    });

    await writeFile(path.join(value.root, 'agents', 'Explore.md'), 'changed');
    await expect(checkActiveContentProjection(active)).rejects.toMatchObject({
      code: 'ACTIVE_CONTENT_TAMPERED',
    });
    await expect(readFile(value.manifestPath, 'utf8')).resolves.toContain(
      '"includedInFileMap": false',
    );
  });
});
