import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { run } from '../../src/main.js';
import { captureIo } from '../../src/io.js';

const hash = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');
async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), 'mpx-content-cli-'));
  const skill = Buffer.from('exact skill bytes\r\n');
  const agent = Buffer.from('exact agent bytes\n');
  await mkdir(path.join(root, 'skills', 'alpha'), { recursive: true });
  await mkdir(path.join(root, 'agents'));
  await writeFile(path.join(root, 'skills', 'alpha', 'SKILL.md'), skill);
  await writeFile(path.join(root, 'agents', 'Explore.md'), agent);
  const files = [
    { relativePath: 'agents/Explore.md', sha256: hash(agent), byteCount: agent.byteLength },
    { relativePath: 'skills/alpha/SKILL.md', sha256: hash(skill), byteCount: skill.byteLength },
  ];
  const manifest = {
    schemaVersion: 1,
    compilerVersion: '1.0.0',
    runtime: 'claude',
    profileSchemaVersion: 1,
    binding: { projectId: null, repositoryId: 'repo', contentScope: 'test' },
    manifestKey: 'key',
    manifestEnvelope: { path: 'active-content.json', includedInFileMap: false },
    skills: [
      {
        identity: 'alpha',
        exposure: 'name-only',
        canonicalDescription: 'Canonical alpha.',
        effectiveDescription: 'Effective alpha.',
        sourcePath: 'alpha/SKILL.md',
        generatedPath: files[1]!.relativePath,
        generatedSha256: files[1]!.sha256,
        bodyByteOffset: 0,
        omittedOptionalFeatures: [],
      },
    ],
    agents: [
      {
        canonicalIdentity: 'mpx-explorer',
        projectedIdentity: 'Explore',
        semanticModel: 'standard',
        concreteModel: 'sonnet',
        thinking: 'medium',
        capabilities: ['read'],
        tools: ['Read'],
        nesting: { canonical: [], projected: [], requiredTools: [] },
        outputSchema: 'text',
        sourcePath: 'mpx-explorer.md',
        sourceSha256: 'a'.repeat(64),
        sourceByteCount: 1,
        generatedPath: files[0]!.relativePath,
        generatedSha256: files[0]!.sha256,
        generatedByteCount: files[0]!.byteCount,
      },
    ],
    files,
  };
  const manifestPath = path.join(root, 'active-content.json');
  await writeFile(manifestPath, `${JSON.stringify(manifest)}\n`);
  return {
    root,
    manifestPath,
    skill,
    agent,
    env: { MPX_ACTIVE_CONTENT_ROOT: root, MPX_ACTIVE_CONTENT_MANIFEST: manifestPath },
  };
}

describe('content command', () => {
  it('prints focused help successfully for the bare group', async () => {
    const io = captureIo();
    expect(await run(['content'], io, { env: {} })).toBe(0);
    expect(io.out.join('')).toContain('current');
    expect(io.out.join('')).not.toContain('diff');
  });

  it('reports exact active paths in human and versioned JSON output', async () => {
    const value = await fixture(),
      human = captureIo(),
      json = captureIo();
    expect(await run(['content', 'current'], human, { env: value.env })).toBe(0);
    expect(human.out.join('')).toBe(`${value.root}\n${value.manifestPath}\n`);
    expect(await run(['content', 'current', '--json'], json, { env: value.env })).toBe(0);
    expect(JSON.parse(json.out[0]!)).toEqual({
      apiVersion: 1,
      ok: true,
      data: { root: value.root, manifest: value.manifestPath },
      warnings: [],
    });
  });

  it('lists concise skill and agent inspection fields from the persisted manifest', async () => {
    const value = await fixture(),
      io = captureIo();
    expect(await run(['content', 'list', '--json'], io, { env: value.env })).toBe(0);
    expect(JSON.parse(io.out[0]!).data).toEqual({
      skills: [
        {
          identity: 'alpha',
          path: 'skills/alpha/SKILL.md',
          exposure: 'name-only',
          description: 'Effective alpha.',
        },
      ],
      agents: [
        {
          identity: 'mpx-explorer',
          projectedIdentity: 'Explore',
          path: 'agents/Explore.md',
          model: 'sonnet',
        },
      ],
    });
  });

  it('shows exact generated bytes without rebuilding', async () => {
    const value = await fixture(),
      skillIo = captureIo(),
      agentIo = captureIo();
    expect(await run(['content', 'show', 'skill', 'alpha'], skillIo, { env: value.env })).toBe(0);
    expect(Buffer.from(skillIo.out.join(''))).toEqual(value.skill);
    expect(await run(['content', 'show', 'agent', 'Explore'], agentIo, { env: value.env })).toBe(0);
    expect(Buffer.from(agentIo.out.join(''))).toEqual(value.agent);
  });

  it('reports structured unavailability and tamper failures', async () => {
    const missing = captureIo();
    expect(await run(['content', 'current', '--json'], missing, { env: {} })).toBe(1);
    expect(JSON.parse(missing.out[0]!).error.code).toBe('ACTIVE_CONTENT_UNAVAILABLE');
    const value = await fixture(),
      clean = captureIo();
    expect(await run(['content', 'check'], clean, { env: value.env })).toBe(0);
    expect(clean.out.join('')).toContain('clean');
    await writeFile(path.join(value.root, 'agents', 'Explore.md'), 'tampered');
    const changed = captureIo();
    expect(await run(['content', 'check', '--json'], changed, { env: value.env })).toBe(1);
    expect(JSON.parse(changed.out[0]!).error.code).toBe('ACTIVE_CONTENT_TAMPERED');
  });
});
