import { createHash, randomUUID } from "node:crypto";
import { PassThrough } from "node:stream";
import type { RemoteToolClient, RemoteResult, SandboxRuntimeHandle } from "@mpx/executors";
import type { ManagedProcess, ProcessExit, RuntimeAdapter, StartRequest } from "./index.js";
export type { SandboxRuntimeHandle } from "@mpx/executors";
const SHA=/^[a-f0-9]{64}$/u;
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
interface BoundSandboxHandle extends SandboxRuntimeHandle {readonly appNamespace:string;send(line:string,signal?:AbortSignal):Promise<string>;readOutput(requestId:string):Promise<string>;publishedPort(assignedPort:number):{readonly host:"127.0.0.1";readonly port:number}}
class DockerProcess implements ManagedProcess {readonly stdout=new PassThrough();readonly stderr=new PassThrough();readonly closed:Promise<ProcessExit>;private finish!:(exit:ProcessExit)=>void;private exit?:ProcessExit;private listeners:((exit:ProcessExit)=>void)[]=[];constructor(readonly pid:number,readonly fingerprint:string){this.closed=new Promise(resolve=>{this.finish=resolve})}onClose(listener:(exit:ProcessExit)=>void){this.exit?listener(this.exit):this.listeners.push(listener)}close(exit:ProcessExit){if(this.exit)return;this.exit=exit;this.finish(exit);this.listeners.splice(0).forEach(listener=>listener(exit))}}
function exactObject<T>(text:string,keys:readonly string[],validate:(value:Record<string,unknown>)=>boolean):T{if(Buffer.byteLength(text)>1_048_576)throw new Error("Sandbox output exceeds bounds.");let value:unknown;try{value=JSON.parse(text)}catch{throw new Error("Sandbox output is invalid JSON.")}if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).sort().join(",")!==[...keys].sort().join(",")||!validate(value as Record<string,unknown>))throw new Error("Sandbox output shape is invalid.");return value as T}
export interface DockerRuntimeOptions {readonly handle:BoundSandboxHandle;readonly client:RemoteToolClient;readonly capabilitySha256:string;readonly binding:{readonly launchKey:string;readonly worktreeRoot:string;readonly assignedPorts:readonly number[]};readonly hostProbe:(host:"127.0.0.1",port:number)=>Promise<boolean>;readonly hostPortAvailable:(host:"127.0.0.1",port:number)=>Promise<boolean>;readonly sleep?:(ms:number)=>Promise<void>;readonly now?:()=>string;readonly signal?:AbortSignal}
export class DockerRuntimeAdapter implements RuntimeAdapter {readonly kind="docker" as const;readonly owned=new Map<number,DockerProcess>();readonly identities=new Map<number,string>();readonly assigned=new Set<number>();readonly handle:BoundSandboxHandle;constructor(readonly options:DockerRuntimeOptions){this.handle=options.handle;if(!this.handle.name||!this.handle.appNamespace||!SHA.test(options.capabilitySha256)||!SHA.test(options.binding.launchKey)||!options.binding.worktreeRoot.startsWith("/")||new Set(options.binding.assignedPorts).size!==options.binding.assignedPorts.length)throw new Error("Docker runtime binding is invalid.")}now=()=>this.options.now?.()??new Date().toISOString();sleep=(ms:number)=>this.options.sleep?.(ms)??new Promise<void>(resolve=>setTimeout(resolve,ms));
 private async call<T>(toolPath:string,payload:unknown,keys:readonly string[],validate:(value:Record<string,unknown>)=>boolean):Promise<T>{if(this.options.signal?.aborted)throw Object.assign(new Error("Docker service operation cancelled."),{code:"ABORT_ERR"});const requestId=`dev-${randomUUID()}`,encoded=JSON.stringify(payload),inputSha256=sha(encoded),requestSha256=sha(JSON.stringify({toolPath,inputSha256,sandbox:this.handle.name,namespace:this.handle.appNamespace}));await this.handle.writeInput?.(requestId,encoded,this.options.signal);const result:RemoteResult=await this.options.client.call({requestId,toolPath,inputSha256,requestSha256,capabilitySha256:this.options.capabilitySha256,...(this.options.signal?{signal:this.options.signal}:{})});if(result.status!=="ok")throw Object.assign(new Error(`Sandbox operation failed: ${result.errorCode??"REMOTE_ERROR"}`),{code:result.errorCode??"REMOTE_ERROR"});const output=await this.handle.readOutput(requestId);if(Buffer.byteLength(output)!==result.outputBytes||sha(output)!==result.outputSha256)throw new Error("Sandbox output integrity mismatch.");return exactObject<T>(output,keys,validate)}
 async spawn(request:StartRequest){if(request.executor!=="docker")throw new Error("Docker adapter refuses a foreign executor request.");if(request.assignment.worktreeRoot!==this.options.binding.worktreeRoot||request.cwd!==this.options.binding.worktreeRoot&&!request.cwd.startsWith(`${this.options.binding.worktreeRoot.replace(/\/$/u,"")}/`))throw new Error("Docker service worktree does not match the immutable launch binding.");if(request.ports.length!==this.options.binding.assignedPorts.length||request.ports.some(port=>!this.options.binding.assignedPorts.includes(port)))throw new Error("Docker service ports do not match the immutable launch binding.");if(request.ports.length!==request.assignment.ports.length||request.ports.some(port=>!request.assignment.ports.includes(port)))throw new Error("Docker service ports must exactly match assigned ports.");for(const port of request.ports){const published=this.handle.publishedPort(port);if(published.host!=="127.0.0.1"||!await this.options.hostPortAvailable(published.host,published.port))throw new Error(`Host-published assigned port conflict for ${port}.`)}const value=await this.call<{pid:number;fingerprint:string}>("dev-services/spawn",{sandboxName:this.handle.name,appNamespace:this.handle.appNamespace,launchKey:this.options.binding.launchKey,executable:request.executable,args:request.args,cwd:request.cwd,environment:request.environment??{},ports:request.ports,publishedPorts:request.ports.map(port=>({assigned:port,...this.handle.publishedPort(port)})),processGroup:true},["pid","fingerprint"],v=>Number.isSafeInteger(v.pid)&&Number(v.pid)>0&&typeof v.fingerprint==="string"&&v.fingerprint.length>0&&v.fingerprint.length<=256);const child=new DockerProcess(value.pid,value.fingerprint);this.owned.set(child.pid,child);this.identities.set(child.pid,child.fingerprint);request.ports.forEach(port=>this.assigned.add(port));return child}
 async probe(port:number){if(!this.assigned.has(port))throw new Error("Probe port is not assigned to this sandbox launch.");const vm=await this.call<{ready:boolean}>("dev-services/probe-vm",{sandboxName:this.handle.name,port},["ready"],v=>typeof v.ready==="boolean");if(!vm.ready)return false;const published=this.handle.publishedPort(port);if(published.host!=="127.0.0.1")throw new Error("Published development-service host must be loopback.");return this.options.hostProbe(published.host,published.port)}
 async inspect(pid:number){if(!Number.isSafeInteger(pid)||pid<=0)return undefined;const value=await this.call<{pid:number;fingerprint:string}>("dev-services/inspect",{sandboxName:this.handle.name,pid},["pid","fingerprint"],v=>v.pid===pid&&typeof v.fingerprint==="string");this.identities.set(pid,value.fingerprint);return value}
 async logs(pid:number){if(!this.owned.has(pid))throw new Error("Process is not owned by this sandbox runtime.");const value=await this.call<{stdout:string;stderr:string}>("dev-services/logs",{sandboxName:this.handle.name,pid,maxBytes:20000},["stdout","stderr"],v=>typeof v.stdout==="string"&&typeof v.stderr==="string"&&Buffer.byteLength(v.stdout)+Buffer.byteLength(v.stderr)<=20000);const child=this.owned.get(pid)!;if(value.stdout)child.stdout.write(value.stdout);if(value.stderr)child.stderr.write(value.stderr);return value}
 private requireOwned(child:ManagedProcess){const known=this.identities.get(child.pid);if(known!==child.fingerprint)throw new Error("Sandbox process-group ownership fingerprint does not match; refusing foreign kill.");return this.owned.get(child.pid)??child}
 async restart(child:ManagedProcess){const owned=this.requireOwned(child);const value=await this.call<{pid:number;fingerprint:string}>("dev-services/restart",{sandboxName:this.handle.name,pid:owned.pid,fingerprint:owned.fingerprint,processGroup:true},["pid","fingerprint"],v=>Number.isSafeInteger(v.pid)&&Number(v.pid)>0&&typeof v.fingerprint==="string");if(value.pid===owned.pid&&value.fingerprint===owned.fingerprint)return owned;this.owned.delete(owned.pid);this.identities.delete(owned.pid);if(owned instanceof DockerProcess)owned.close({code:null,signal:"RESTART"});const replacement=new DockerProcess(value.pid,value.fingerprint);this.owned.set(value.pid,replacement);this.identities.set(value.pid,value.fingerprint);return replacement}
 async stop(child:ManagedProcess){const owned=this.requireOwned(child);await this.call<{stopped:boolean}>("dev-services/stop",{sandboxName:this.handle.name,pid:owned.pid,fingerprint:owned.fingerprint,processGroup:true},["stopped"],v=>v.stopped===true);this.owned.delete(owned.pid);this.identities.delete(owned.pid);if(owned instanceof DockerProcess)owned.close({code:null,signal:"SIGTERM"})}}
