import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { readFile } from "node:fs/promises";
import { connect } from "node:net";
import path from "node:path";
import { StringDecoder } from "node:string_decoder";
import type { Readable } from "node:stream";
import { WindowsProcessCapabilities } from "@mpx/windows";

export * from "./tool-adapter.js";

export const DEV_SERVICES_CHANGED_EVENT = "dev-services:changed";
export type DevServiceState = "starting"|"ready"|"crashed"|"stopped";
export type ExecutorKind = "host"|"docker";
export interface PortAssignment { readonly worktreeRoot:string; readonly ports:readonly number[] }
export interface StartRequest { readonly id:string; readonly command:string; readonly cwd:string; readonly ports:readonly number[]; readonly assignment:PortAssignment; readonly executor:ExecutorKind }
export interface ProcessExit {readonly code:number|null;readonly signal:string|null}
export interface ManagedProcess {readonly pid:number;readonly fingerprint:string;readonly stdout:Readable;readonly stderr:Readable;readonly closed:Promise<ProcessExit>;onClose(listener:(exit:ProcessExit)=>void):void;onError?(listener:(error:Error)=>void):void}
export interface RuntimeAdapter {readonly kind:ExecutorKind;spawn(request:Pick<StartRequest,"command"|"cwd">):ManagedProcess|Promise<ManagedProcess>;probe(port:number):Promise<boolean>;inspect(pid:number):Promise<{pid:number;fingerprint:string}|undefined>;stop(process:ManagedProcess):Promise<void>;sleep(ms:number):Promise<void>;now():string}
export interface DevServiceSnapshot {readonly id:string;readonly state:DevServiceState;readonly pid:number|null;readonly fingerprint:string|null;readonly cwd:string;readonly command:string;readonly ports:readonly number[];readonly readyPorts:readonly number[];readonly run:number;readonly generation:number;readonly createdAt:string;readonly startedAt:string|null;readonly readyAt:string|null;readonly stoppedAt:string|null;readonly exitedAt:string|null;readonly updatedAt:string;readonly exitCode:number|null;readonly exitSignal:string|null;readonly lastError:string|null}
export interface DevServiceStatusEvent {readonly type:typeof DEV_SERVICES_CHANGED_EVENT;readonly snapshot:DevServiceSnapshot}

function canonical(value:string):string { const win=path.win32.isAbsolute(value); return (win?path.win32.normalize(value).replaceAll("\\","/").toLowerCase():path.resolve(value).replaceAll("\\","/" )).replace(/\/$/u,""); }
function within(root:string,candidate:string):boolean { const r=canonical(root),c=canonical(candidate); return c===r||c.startsWith(`${r}/`); }
export function assertExecutorBoundary(selected:ExecutorKind,runtime:ExecutorKind):void { if(selected!==runtime) throw new Error(selected==="docker"?"Docker executor development services require a Docker runtime adapter; host execution is forbidden.":"Selected executor does not match the development-service runtime."); }
export function validateStartRequest(request:StartRequest):StartRequest {
  if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u.test(request.id)) throw new Error("Dev service id must be a bounded safe label.");
  if(!request.command.trim()||/[\0\r\n]/u.test(request.command)) throw new Error("Dev service command is invalid.");
  if(!path.win32.isAbsolute(request.cwd)&&!path.posix.isAbsolute(request.cwd)) throw new Error("Dev service cwd must be absolute.");
  if(!within(request.assignment.worktreeRoot,request.cwd)) throw new Error("Dev service cwd must remain inside the assigned worktree.");
  const valid=(ports:readonly number[])=>ports.every(p=>Number.isInteger(p)&&p>0&&p<=65535)&&new Set(ports).size===ports.length;
  if(!valid(request.ports)||!valid(request.assignment.ports)||request.ports.length!==request.assignment.ports.length||request.ports.some(p=>!request.assignment.ports.includes(p))) throw new Error("Readiness ports must exactly match ports assigned to this worktree.");
  return Object.freeze({...request,id:request.id,command:request.command.trim(),cwd:canonical(request.cwd),ports:Object.freeze([...request.ports]),assignment:Object.freeze({...request.assignment,worktreeRoot:canonical(request.assignment.worktreeRoot),ports:Object.freeze([...request.assignment.ports])})});
}

type StreamName="stdout"|"stderr";interface StreamState{decoder:StringDecoder;partial:string;pendingCr:boolean}
const controls=/(?:\u001b\][^\u0007]*(?:\u0007|\u001b\\)|\u001bP[\s\S]*?\u001b\\|\u001b\[[0-?]*[ -/]*[@-~]|\u001b[@-_])/gu;
export class RollingLogBuffer {
  readonly max:number;run=0;items:{run:number;stream:StreamName;text:string}[]=[];size=0;states=this.fresh();
  constructor(options:{maxCharacters?:number}={}){this.max=Math.max(1,options.maxCharacters??100000)}
  fresh():Record<StreamName,StreamState>{return{stdout:{decoder:new StringDecoder("utf8"),partial:"",pendingCr:false},stderr:{decoder:new StringDecoder("utf8"),partial:"",pendingCr:false}}}
  beginRun(run:number){this.flush();this.run=run;this.states=this.fresh()}
  write(stream:StreamName,chunk:Uint8Array){this.consume(stream,this.states[stream].decoder.write(chunk))}
  flush(){for(const stream of ["stdout","stderr"] as const){const s=this.states[stream];this.consume(stream,s.decoder.end());if(s.pendingCr||s.partial){this.emit(stream,s.partial);s.partial="";s.pendingCr=false}}}
  entries(){return this.items.map(v=>Object.freeze({...v}))}
  present(options:{maxCharacters?:number;maxLines?:number}={}){const chars=Math.max(1,options.maxCharacters??20000),lines=Math.max(1,options.maxLines??200);let text=this.items.slice(-lines).map(v=>v.text.replace(controls,"")).join("\n");if(text.length>chars)text=chars===1?"…":`…${text.slice(-(chars-1))}`;return text}
  consume(stream:StreamName,text:string){const s=this.states[stream];for(const char of text){if(s.pendingCr){s.pendingCr=false;if(char==="\n"){this.emit(stream,s.partial);s.partial="";continue}s.partial=""}if(char==="\r")s.pendingCr=true;else if(char==="\n"){this.emit(stream,s.partial);s.partial=""}else{s.partial+=char;if(s.partial.length>this.max)s.partial=s.partial.slice(-this.max)}}}
  emit(stream:StreamName,text:string){if(!text)return;const bounded=text.slice(-this.max);this.items.push(Object.freeze({run:this.run,stream,text:bounded}));this.size+=bounded.length;while(this.size>this.max){const old=this.items.shift()!;this.size-=old.text.length}}
}

interface RecordState {request:StartRequest;state:DevServiceState;child:ManagedProcess|null;pid:number|null;fingerprint:string|null;readyPorts:number[];run:number;generation:number;createdAt:string;startedAt:string|null;readyAt:string|null;stoppedAt:string|null;exitedAt:string|null;updatedAt:string;exitCode:number|null;exitSignal:string|null;lastError:string|null;stopRequested:boolean;queue:Promise<void>;logs:RollingLogBuffer;readiness:Promise<void>|null}
export class DevServiceManager {
  readonly records=new Map<string,RecordState>(); shuttingDown=false; shutdownTask?:Promise<void>;
  constructor(readonly runtime:RuntimeAdapter,readonly publish:(event:DevServiceStatusEvent)=>void=()=>{},readonly readinessIntervalMs=200){}
  start(input:StartRequest):Promise<DevServiceSnapshot>{try{if(this.shuttingDown)throw new Error("Dev service manager is shutting down.");assertExecutorBoundary(input.executor,this.runtime.kind);const request=validateStartRequest(input);if(this.records.has(request.id))throw new Error(`Dev service '${request.id}' already exists.`);const now=this.runtime.now();const record:RecordState={request,state:"starting",child:null,pid:null,fingerprint:null,readyPorts:[],run:0,generation:0,createdAt:now,startedAt:null,readyAt:null,stoppedAt:null,exitedAt:null,updatedAt:now,exitCode:null,exitSignal:null,lastError:null,stopRequested:false,queue:Promise.resolve(),logs:new RollingLogBuffer(),readiness:null};this.records.set(request.id,record);return this.launch(record)}catch(e){return Promise.reject(e)}}
  status(id:string){const r=this.records.get(id);return r?this.snapshot(r):undefined} list(){return [...this.records.values()].map(r=>this.snapshot(r))} logs(id:string,o:{maxCharacters?:number;maxLines?:number}={}){return this.require(id).logs.present(o)} logEntries(id:string){return this.require(id).logs.entries()}
  stop(id:string){const r=this.require(id);if(r.child)r.stopRequested=true;return this.enqueue(r,async()=>{await this.stopInternal(r);return this.snapshot(r)})}
  restart(id:string){if(this.shuttingDown)return Promise.reject(new Error("Dev service manager is shutting down."));const r=this.require(id);return this.enqueue(r,async()=>{await this.stopInternal(r);return this.launch(r)})}
  shutdown(){if(this.shutdownTask)return this.shutdownTask;this.shuttingDown=true;const records=[...this.records.values()];records.forEach(r=>{if(r.child)r.stopRequested=true});this.shutdownTask=(async()=>{const results=await Promise.allSettled(records.map(r=>this.enqueue(r,()=>this.stopInternal(r))));const errors=results.filter((v):v is PromiseRejectedResult=>v.status==="rejected").map(v=>v.reason);if(errors.length)throw new AggregateError(errors,"Failed to clean up managed development services.")})();return this.shutdownTask}
  async reconcile():Promise<readonly DevServiceSnapshot[]>{for(const r of this.records.values()){if(!r.child)continue;const identity=await this.runtime.inspect(r.child.pid);if(identity&&identity.pid===r.child.pid&&identity.fingerprint===r.fingerprint)continue;r.generation+=1;r.logs.flush();r.child=null;r.pid=null;r.fingerprint=null;r.state="crashed";r.exitedAt=this.runtime.now();r.lastError="Owned process is absent or its fingerprint no longer matches.";this.emit(r)}return this.list()}
  async launch(r:RecordState){const generation=++r.generation;r.run++;r.state="starting";r.stopRequested=false;r.readyPorts=[];r.startedAt=this.runtime.now();r.readyAt=r.stoppedAt=r.exitedAt=null;r.exitCode=r.exitSignal=r.lastError=null;r.logs.beginRun(r.run);let child:ManagedProcess;try{child=await this.runtime.spawn(r.request)}catch(e){r.state="crashed";r.exitedAt=this.runtime.now();r.lastError=e instanceof Error?e.message:String(e);this.emit(r);return this.snapshot(r)}r.child=child;r.pid=child.pid;r.fingerprint=child.fingerprint;child.stdout.on("data",c=>{if(r.generation===generation)r.logs.write("stdout",c)});child.stderr.on("data",c=>{if(r.generation===generation)r.logs.write("stderr",c)});child.onClose(exit=>this.closed(r,generation,exit));child.onError?.(error=>{if(r.generation===generation){r.lastError=error.message;this.emit(r)}});this.emit(r);if(!r.request.ports.length)this.ready(r,generation,[]);else{const task=this.monitor(r,generation);r.readiness=task;void task.finally(()=>{if(r.readiness===task)r.readiness=null})}return this.snapshot(r)}
  async monitor(r:RecordState,g:number){while(r.generation===g&&r.state==="starting"&&!r.stopRequested){const results=await Promise.all(r.request.ports.map(async port=>({port,ready:await this.runtime.probe(port)})));if(r.generation!==g||r.state!=="starting"||r.stopRequested)return;const ready=results.filter(v=>v.ready).map(v=>v.port);if(JSON.stringify(ready)!==JSON.stringify(r.readyPorts)){r.readyPorts=ready;this.emit(r)}if(ready.length===r.request.ports.length){this.ready(r,g,ready);return}await this.runtime.sleep(this.readinessIntervalMs)}}
  ready(r:RecordState,g:number,ports:number[]){if(r.generation!==g||r.state!=="starting")return;r.state="ready";r.readyPorts=[...ports];r.readyAt=this.runtime.now();this.emit(r)}
  closed(r:RecordState,g:number,exit:ProcessExit){if(r.generation!==g)return;const requested=r.stopRequested;r.logs.flush();r.child=null;r.pid=null;r.fingerprint=null;r.exitedAt=this.runtime.now();r.exitCode=exit.code;r.exitSignal=exit.signal;r.state=requested?"stopped":"crashed";if(requested)r.stoppedAt=r.exitedAt;this.emit(r)}
  async stopInternal(r:RecordState){const child=r.child;if(!child||r.state==="stopped"||r.state==="crashed")return;r.stopRequested=true;const identity=await this.runtime.inspect(child.pid);if(!identity||identity.pid!==child.pid||identity.fingerprint!==r.fingerprint){r.lastError="Process ownership fingerprint no longer matches; refusing termination.";this.emit(r);throw new Error(r.lastError)}await this.runtime.stop(child);await child.closed}
  enqueue<T>(r:RecordState,fn:()=>Promise<T>){const out=r.queue.then(fn,fn);r.queue=out.then(()=>undefined,()=>undefined);return out} require(id:string){const r=this.records.get(id);if(!r)throw new Error(`Unknown dev service '${id}'.`);return r}
  emit(r:RecordState){r.updatedAt=this.runtime.now();this.publish(Object.freeze({type:DEV_SERVICES_CHANGED_EVENT,snapshot:this.snapshot(r)}))}
  snapshot(r:RecordState):DevServiceSnapshot{return Object.freeze({id:r.request.id,state:r.state,pid:r.pid,fingerprint:r.fingerprint,cwd:r.request.cwd,command:r.request.command,ports:Object.freeze([...r.request.ports]),readyPorts:Object.freeze([...r.readyPorts]),run:r.run,generation:r.generation,createdAt:r.createdAt,startedAt:r.startedAt,readyAt:r.readyAt,stoppedAt:r.stoppedAt,exitedAt:r.exitedAt,updatedAt:r.updatedAt,exitCode:r.exitCode,exitSignal:r.exitSignal,lastError:r.lastError})}
}

const wait=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
class SystemProcess implements ManagedProcess {readonly pid:number;readonly fingerprint:string;readonly stdout;readonly stderr;readonly closed:Promise<ProcessExit>;exit?:ProcessExit;error?:Error;listeners:((e:ProcessExit)=>void)[]=[];errorListeners:((e:Error)=>void)[]=[];constructor(readonly process:ChildProcessWithoutNullStreams,fingerprint:string){if(process.pid===undefined)throw new Error("Spawned service has no pid.");this.pid=process.pid;this.fingerprint=fingerprint;this.stdout=process.stdout;this.stderr=process.stderr;this.closed=new Promise(resolve=>process.once("close",(code,signal)=>{const e={code,signal};this.exit=e;resolve(e);this.listeners.splice(0).forEach(fn=>fn(e))}));process.once("error",e=>{this.error=e;this.errorListeners.splice(0).forEach(fn=>fn(e))})}onClose(fn:(e:ProcessExit)=>void){this.exit?fn(this.exit):this.listeners.push(fn)}onError(fn:(e:Error)=>void){this.error?fn(this.error):this.errorListeners.push(fn)}}
export function systemSpawnInvocation(command:string,platform=process.platform){return platform==="win32"?{file:"cmd.exe",args:["/d","/s","/c",command],detached:false}:{file:"/bin/sh",args:["-c",command],detached:true}}
export function createSystemRuntime():RuntimeAdapter {const identities=new Map<number,string>(),windows=new WindowsProcessCapabilities();const inspectOs=async(pid:number):Promise<string|undefined>=>{if(process.platform==="win32")return (await windows.inspect(pid))?.startFingerprint;if(process.platform==="linux"){try{const fields=(await readFile(`/proc/${pid}/stat`,"utf8")).split(" ");return fields[21]}catch{return undefined}}try{process.kill(pid,0);return identities.get(pid)}catch{return undefined}};return{kind:"host",now:()=>new Date().toISOString(),sleep:wait,async spawn(request){const invocation=systemSpawnInvocation(request.command);const processHandle=spawn(invocation.file,invocation.args,{cwd:request.cwd,detached:invocation.detached,stdio:["ignore","pipe","pipe"],windowsHide:true}) as unknown as ChildProcessWithoutNullStreams;if(processHandle.pid===undefined)throw new Error("Spawned service has no pid.");const fingerprint=await inspectOs(processHandle.pid);if(!fingerprint){processHandle.kill();throw new Error("Spawned service process fingerprint is unavailable.")}const child=new SystemProcess(processHandle,fingerprint);identities.set(child.pid,child.fingerprint);void child.closed.finally(()=>identities.delete(child.pid));return child},async inspect(pid){const fingerprint=await inspectOs(pid);return fingerprint?{pid,fingerprint}:undefined},probe(port){return new Promise(resolve=>{const socket=connect({host:"localhost",port});let done=false;const finish=(v:boolean)=>{if(done)return;done=true;socket.destroy();resolve(v)};socket.setTimeout(400);socket.once("connect",()=>finish(true));socket.once("timeout",()=>finish(false));socket.once("error",()=>finish(false))})},async stop(child){if(process.platform==="win32")await windows.terminateTree({pid:child.pid,startFingerprint:child.fingerprint});else{try{process.kill(-child.pid,"SIGTERM")}catch(e){if((e as NodeJS.ErrnoException).code!=="ESRCH")throw e}await Promise.race([child.closed,wait(5000)]);try{process.kill(-child.pid,"SIGKILL")}catch(e){if((e as NodeJS.ErrnoException).code!=="ESRCH")throw e}}}}}
