import { randomUUID } from "node:crypto";
import { createConnection } from "node:net";
import { RUNTIME_TOOL_INVENTORY_SHA256 } from "@mpx/runtime-tools";
import { PHASE_F2_REMOTE_ATTESTATION_PATHS, type PiRemoteExecutor } from "./sandbox-executor.js";

const MAX=1024*1024, SHA=/^[a-f0-9]{64}$/u;
export interface LaunchPrivateClientConfig {readonly schemaVersion:1;readonly endpoint:string;readonly nonce:string;readonly launchKey:string;readonly identity:{readonly name:string;readonly domain:"personal"|"work"};readonly planKey:string;readonly runtimeToolInventorySha256:string;readonly capabilitySha256:string}
function failure(code:string):Error&{code:string}{return Object.assign(new Error(code),{code})}
export function parseLaunchPrivateClientConfig(text:string|undefined,expected:{launchKey:string;identity:{name:string;domain:string};capabilitySha256?:string}):LaunchPrivateClientConfig{
 let value:unknown;try{if(!text||Buffer.byteLength(text)>16_384)throw new Error();value=JSON.parse(text)}catch{throw failure("BRIDGE_CONFIG_REQUIRED")}
 const keys=["schemaVersion","endpoint","nonce","launchKey","identity","planKey","runtimeToolInventorySha256","capabilitySha256"];
 if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).sort().join(",")!==keys.sort().join(","))throw failure("BRIDGE_CONFIG_INVALID");const item=value as Record<string,unknown>,identity=item.identity as Record<string,unknown>;
 if(item.schemaVersion!==1||typeof item.endpoint!=="string"||!/^tcp:\/\/127\.0\.0\.1:\d{1,5}$/u.test(item.endpoint)||typeof item.nonce!=="string"||!SHA.test(item.nonce)||![item.launchKey,item.planKey,item.runtimeToolInventorySha256,item.capabilitySha256].every(v=>typeof v==="string"&&SHA.test(v))||!identity||Object.keys(identity).sort().join(",")!=="domain,name"||identity.name!==expected.identity.name||identity.domain!==expected.identity.domain||item.launchKey!==expected.launchKey||(expected.capabilitySha256!==undefined&&item.capabilitySha256!==expected.capabilitySha256)||item.runtimeToolInventorySha256!==RUNTIME_TOOL_INVENTORY_SHA256)throw failure("BRIDGE_ATTESTATION_FAILED");return Object.freeze({...item,identity:Object.freeze({...identity})}) as unknown as LaunchPrivateClientConfig;
}
export function createLaunchPrivateRemoteExecutor(config:LaunchPrivateClientConfig):PiRemoteExecutor{
 const seen=new Set<string>();return {attestation:()=>({toolPaths:PHASE_F2_REMOTE_ATTESTATION_PATHS,digest:config.capabilitySha256,inventorySha256:config.runtimeToolInventorySha256}),execute:async(toolPath,input)=>{const requestId=randomUUID();if(seen.has(requestId))throw failure("REMOTE_REPLAY");seen.add(requestId);const port=Number(config.endpoint.slice(config.endpoint.lastIndexOf(":")+1));const frame={schemaVersion:1,kind:"request",requestId,nonce:config.nonce,launchKey:config.launchKey,identity:config.identity,planKey:config.planKey,runtimeToolInventorySha256:config.runtimeToolInventorySha256,capabilitySha256:config.capabilitySha256,toolPath,input},encoded=`${JSON.stringify(frame)}\n`;if(Buffer.byteLength(encoded)>MAX)throw failure("BRIDGE_FRAME_INVALID");return new Promise((resolve,reject)=>{const socket=createConnection({host:"127.0.0.1",port});let bytes=Buffer.alloc(0),done=false;const finish=(error?:unknown,output?:unknown)=>{if(done)return;done=true;socket.destroy();error?reject(error):resolve(output)};socket.once("error",()=>finish(failure("BRIDGE_UNAVAILABLE")));socket.once("connect",()=>socket.write(encoded));socket.on("data",chunk=>{bytes=Buffer.concat([bytes,chunk]);if(bytes.length>MAX)return finish(failure("BRIDGE_FRAME_INVALID"));const newline=bytes.indexOf(10);if(newline<0)return;if(newline!==bytes.length-1)return finish(failure("BRIDGE_FRAME_INVALID"));try{const reply=JSON.parse(bytes.toString("utf8")) as Record<string,unknown>;if(reply.kind==="error")return finish(failure(String(reply.code)));if(Object.keys(reply).sort().join(",")!=="kind,output,requestId,schemaVersion"||reply.schemaVersion!==1||reply.kind!=="result"||reply.requestId!==requestId)return finish(failure("BRIDGE_STALE_RESULT"));finish(undefined,reply.output)}catch{finish(failure("BRIDGE_FRAME_INVALID"))}})})}};
}
