import { createHash } from "node:crypto";
import { mkdir, lstat, open, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { MpxError, type JsonValue } from "@mpx/core";
import { ISSUE_CAPABILITIES, LOCAL_ISSUE_CAPABILITIES, ProviderError, type IssueCommentV1, type IssueV1, type ProviderAdapter, type ProviderInvocation } from "@mpx/providers";

export interface LocalRelationships { parent?: string; children: string[]; related: string[]; duplicates: string[] }
export interface LocalDependencies { dependsOn: string[]; blocks: string[]; frontier: string[]; cycle?: boolean }
export interface LocalIssue extends IssueV1 { readonly providerData: { readonly local: Readonly<Record<string, JsonValue>> } }
export interface BoardPromotionAdapter { promote(issue: LocalIssue, destination: string): Promise<LocalIssue | void> }
export interface LocalIssueStoreOptions { staleLockMilliseconds?: number; promotion?: BoardPromotionAdapter; projectId?: string; onChanged?: (issue: LocalIssue) => Promise<void> }
export interface LocalIssueCreate { title:string; body:string; labels?:string[]; localState?:string; kind?:string; priority?:string; assignees?:string[]; plan?:string; effort?:string; capture?:string }
export interface LocalIssuePatch { title?:string; body?:string; state?:"open"|"finished"; localState?:string; labels?:string[]; relationships?:Partial<LocalRelationships>; kind?:string; priority?:string; assignees?:string[]; plan?:string; effort?:string; capture?:string; blockedBy?:string[]; blocks?:string[]; related?:string[] }

export class LocalIssueError extends MpxError {
  constructor(code:string,message:string,details?:Record<string,JsonValue>){super({code,message,retryable:code==="LOCAL_ISSUE_CONFLICT",...(details?{details}:{})});this.name="LocalIssueError";}
}
interface Document { schemaVersion:2; id:string; project:string; title:string; kind:string; priority:string; labels:string[]; assignees:string[]; state:"open"|"finished"; localState:string; createdAt:string; updatedAt:string; finishedAt?:string; plan:string; effort:string; capture:string; blockedBy:string[]; blocks:string[]; related:string[]; relationships:LocalRelationships; body:string; preservedBody:string; unknown:string[]; revision:string }
interface Index { schemaVersion:1; next:number; files:Record<string,string> }
const safeId=/^(?:0|[1-9][0-9]{0,15})$/u;
const filePattern=/^(\d{6,})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/u;
const marker="<!-- mpx:preserve -->";
const knownKeys=new Set(["schemaVersion","id","project","title","kind","priority","labels","assignees","state","localState","createdAt","updatedAt","finishedAt","plan","effort","capture","blockedBy","blocks","related","relationships"]);
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
const ids=(value:unknown):string[]=>Array.isArray(value)&&value.every(item=>typeof item==="string"&&safeId.test(item))?[...new Set(value)].sort((a,b)=>Number(a)-Number(b)):[];
const strings=(value:unknown):string[]=>Array.isArray(value)&&value.every(item=>typeof item==="string")?[...new Set(value)].sort():[];
export function localIssueSlug(title:string):string { const result=title.normalize("NFKD").replace(/[\u0300-\u036f]/gu,"").toLowerCase().replace(/[^a-z0-9]+/gu,"-").replace(/^-+|-+$/gu,"").slice(0,64).replace(/-+$/u,""); return result||"issue"; }
export function localIssueFilename(id:string,title:string):string { if(!safeId.test(id))throw new LocalIssueError("LOCAL_ISSUE_PATH_UNSAFE","The local issue identifier is unsafe.");return `${id.padStart(6,"0")}-${localIssueSlug(title)}.md`; }
async function assertNoSymlink(candidate:string):Promise<void>{const absolute=path.resolve(candidate),parsed=path.parse(absolute);let cursor=parsed.root;for(const segment of absolute.slice(parsed.root.length).split(path.sep).filter(Boolean)){cursor=path.join(cursor,segment);try{if((await lstat(cursor)).isSymbolicLink())throw new LocalIssueError("LOCAL_ISSUE_PATH_UNSAFE","Local issue paths may not contain symbolic links.");}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return;throw error;}}}
function malformed(){return new LocalIssueError("LOCAL_ISSUE_MALFORMED","The local issue document is malformed.");}
function parseDocument(text:string,expectedId:string):Document { const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/u.exec(text);if(!match)throw malformed();const values:Record<string,unknown>={},unknown:string[]=[];for(const line of match[1]!.split(/\r?\n/u)){const field=/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/u.exec(line);if(!field||!knownKeys.has(field[1]!)){unknown.push(line);continue;}try{values[field[1]!]=JSON.parse(field[2]!);}catch{throw malformed();}}
  if(values.schemaVersion!==2||values.id!==expectedId||typeof values.project!=="string"||typeof values.title!=="string"||typeof values.kind!=="string"||typeof values.priority!=="string"||!Array.isArray(values.labels)||!Array.isArray(values.assignees)||!['open','finished'].includes(String(values.state))||typeof values.localState!=="string"||typeof values.createdAt!=="string"||typeof values.updatedAt!=="string"||typeof values.plan!=="string"||typeof values.effort!=="string"||typeof values.capture!=="string")throw malformed();
  const rel=values.relationships as Record<string,unknown>|undefined;if(rel!==undefined&&(typeof rel!=="object"||rel===null))throw malformed();const raw=match[2]!,at=raw.indexOf(marker);return {schemaVersion:2,id:expectedId,project:values.project,title:values.title,kind:values.kind,priority:values.priority,labels:strings(values.labels),assignees:strings(values.assignees),state:values.state as "open"|"finished",localState:values.localState,createdAt:values.createdAt,updatedAt:values.updatedAt,...(typeof values.finishedAt==="string"?{finishedAt:values.finishedAt}:{}),plan:values.plan,effort:values.effort,capture:values.capture,blockedBy:ids(values.blockedBy),blocks:ids(values.blocks),related:ids(values.related),relationships:{...(typeof rel?.parent==="string"&&safeId.test(rel.parent)?{parent:rel.parent}:{}),children:ids(rel?.children),related:ids(rel?.related),duplicates:ids(rel?.duplicates)},body:at<0?raw:raw.slice(0,at).trimEnd(),preservedBody:at<0?"":raw.slice(at),unknown,revision:digest(text)}; }
function encode(d:Omit<Document,"revision">):string { const fields:[string,unknown][]=[["schemaVersion",2],["id",d.id],["project",d.project],["title",d.title],["kind",d.kind],["priority",d.priority],["labels",d.labels],["assignees",d.assignees],["state",d.state],["localState",d.localState],["createdAt",d.createdAt],["updatedAt",d.updatedAt],...(d.finishedAt?[["finishedAt",d.finishedAt] as [string,unknown]]:[]),["plan",d.plan],["effort",d.effort],["capture",d.capture],["blockedBy",d.blockedBy],["blocks",d.blocks],["related",d.related],["relationships",d.relationships]];const body=d.preservedBody?`${d.body.trimEnd()}\n\n${d.preservedBody}`:d.body;return `---\n${[...fields.map(([k,v])=>`${k}: ${JSON.stringify(v)}`),...d.unknown].join("\n")}\n---\n${body}`; }
async function atomicWrite(file:string,text:string):Promise<void>{const temporary=`${file}.${process.pid}.${Math.random().toString(16).slice(2)}.tmp`;try{await writeFile(temporary,text,{encoding:"utf8",flag:"wx"});await rename(temporary,file);}finally{await rm(temporary,{force:true}).catch(()=>undefined);}}

export class LocalIssueStore {
  readonly root:string;readonly options:Required<Pick<LocalIssueStoreOptions,"staleLockMilliseconds"|"projectId">>&LocalIssueStoreOptions;
  constructor(root:string,options:LocalIssueStoreOptions={}){if(!path.isAbsolute(root))throw new LocalIssueError("LOCAL_ISSUE_ROOT_INVALID","The local issue root must be absolute.");const resolved=path.resolve(root);if(/(?:^|[\\/])(?:\.git|\.mpx|node_modules)(?:[\\/]|$)/ui.test(resolved))throw new LocalIssueError("LOCAL_ISSUE_ROOT_INVALID","The local issue root may not be private native state.");this.root=resolved;this.options={staleLockMilliseconds:options.staleLockMilliseconds??30000,projectId:options.projectId??"local/unknown",...options};}
  async #ready(){await assertNoSymlink(this.root);await mkdir(this.root,{recursive:true});await assertNoSymlink(this.root);}
  async #locked<T>(operation:()=>Promise<T>):Promise<T>{await this.#ready();const lock=path.join(this.root,".mpx-issues.lock"),deadline=Date.now()+5000;while(true){try{const handle=await open(lock,"wx");await handle.writeFile(JSON.stringify({pid:process.pid,createdAt:Date.now()}));await handle.close();break;}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;try{if(Date.now()-(await stat(lock)).mtimeMs>this.options.staleLockMilliseconds){await rm(lock,{force:true});continue;}}catch{continue;}if(Date.now()>deadline)throw new LocalIssueError("LOCAL_ISSUE_LOCK_TIMEOUT","Timed out waiting for the local issue lock.");await new Promise(resolve=>setTimeout(resolve,10));}}try{return await operation();}finally{await rm(lock,{force:true});}}
  async #index():Promise<Index>{await this.#ready();try{const value=JSON.parse(await readFile(path.join(this.root,".mpx-index.json"),"utf8")) as Index;if(value.schemaVersion!==1||!Number.isSafeInteger(value.next)||typeof value.files!=="object")throw malformed();return value;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;const files:Record<string,string>={};let next=1;for(const name of await readdir(this.root)){const match=filePattern.exec(name);if(match){const id=String(Number(match[1]));files[id]=name;next=Math.max(next,Number(id)+1);}}return {schemaVersion:1,next,files};}}
  async #read(id:string):Promise<Document>{if(!safeId.test(id))throw new LocalIssueError("LOCAL_ISSUE_PATH_UNSAFE","The local issue identifier is unsafe.");const index=await this.#index(),name=index.files[id];if(!name||!filePattern.test(name))throw new LocalIssueError("LOCAL_ISSUE_NOT_FOUND",`Local issue ${id} was not found.`);const file=path.join(this.root,name);await assertNoSymlink(file);try{return parseDocument(await readFile(file,"utf8"),id);}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")throw new LocalIssueError("LOCAL_ISSUE_NOT_FOUND",`Local issue ${id} was not found.`);throw error;}}
  async #validate(document:Document):Promise<void>{for(const [relationship,values] of [["blockedBy",document.blockedBy],["blocks",document.blocks],["related",document.related],["parent",document.relationships.parent?[document.relationships.parent]:[]],["children",document.relationships.children]] as const)for(const referenceId of values)try{await this.#read(referenceId);}catch(error){if(error instanceof LocalIssueError&&error.code==="LOCAL_ISSUE_NOT_FOUND")throw new LocalIssueError("LOCAL_ISSUE_REFERENCE_MISSING",`Issue ${document.id} has a missing ${relationship} reference to ${referenceId}.`,{issueId:document.id,referenceId,relationship});throw error;}}
  async #frontier(id:string,direct:string[]):Promise<{frontier:string[];cycle:boolean}>{const leaves=new Set<string>(),visiting=new Set<string>(),seen=new Set<string>();let cycle=false;const walk=async(current:string):Promise<void>=>{if(current===id||visiting.has(current)){cycle=true;return;}if(seen.has(current))return;visiting.add(current);seen.add(current);const doc=await this.#read(current);if(doc.state==="finished"){visiting.delete(current);return;}if(doc.blockedBy.length===0)leaves.add(current);else for(const next of doc.blockedBy)await walk(next);visiting.delete(current);};for(const dependency of direct)await walk(dependency);return {frontier:cycle?[]:[...leaves].sort((a,b)=>Number(a)-Number(b)),cycle};}
  async #normalized(d:Document):Promise<LocalIssue>{await this.#validate(d);const derived=await this.#frontier(d.id,d.blockedBy);return {schemaVersion:1,id:d.id,title:d.title,body:d.body,state:d.state,labels:d.labels,providerData:{local:{nativeId:d.id,project:d.project,kind:d.kind,priority:d.priority,assignees:d.assignees,localState:d.localState,createdAt:d.createdAt,updatedAt:d.updatedAt,...(d.finishedAt?{finishedAt:d.finishedAt}:{}),plan:d.plan,effort:d.effort,capture:d.capture,blockedBy:d.blockedBy,blocks:d.blocks,related:d.related,relationships:d.relationships as unknown as JsonValue,dependencies:{dependsOn:d.blockedBy,blocks:d.blocks,frontier:derived.frontier,...(derived.cycle?{cycle:true}:{})} as unknown as JsonValue,revision:d.revision}}};}
  async #changed(issue:LocalIssue){await this.options.onChanged?.(issue);return issue;}
  async list(state?:"open"|"finished"){const index=await this.#index(),result:LocalIssue[]=[];for(const id of Object.keys(index.files).sort((a,b)=>Number(a)-Number(b))){const item=await this.view(id);if(!state||item.state===state)result.push(item);}return result;}
  async view(id:string){return this.#normalized(await this.#read(id));}
  async create(input:LocalIssueCreate):Promise<LocalIssue>{return this.#locked(async()=>{const index=await this.#index(),id=String(index.next),now=new Date().toISOString(),name=localIssueFilename(id,input.title),document:Omit<Document,"revision">={schemaVersion:2,id,project:this.options.projectId,title:input.title,kind:input.kind??"task",priority:input.priority??"normal",labels:strings(input.labels??[]),assignees:strings(input.assignees??[]),state:"open",localState:input.localState??"todo",createdAt:now,updatedAt:now,plan:input.plan??"",effort:input.effort??"",capture:input.capture??"",blockedBy:[],blocks:[],related:[],relationships:{children:[],related:[],duplicates:[]},body:input.body,preservedBody:"",unknown:[]};await atomicWrite(path.join(this.root,name),encode(document));index.next++;index.files[id]=name;await atomicWrite(path.join(this.root,".mpx-index.json"),JSON.stringify(index));return this.#changed(await this.view(id));});}
  async update(id:string,patch:LocalIssuePatch,expectedRevision?:string):Promise<LocalIssue>{return this.#locked(async()=>{const current=await this.#read(id);await this.#validate(current);if(expectedRevision!==undefined&&current.revision!==expectedRevision)throw new LocalIssueError("LOCAL_ISSUE_CONFLICT","The local issue changed since it was read.",{id});const index=await this.#index(),oldName=index.files[id]!,newName=localIssueFilename(id,patch.title??current.title),now=new Date().toISOString();const relationships={...current.relationships,...patch.relationships,...(patch.related?{related:ids(patch.related)}:{})};const document:Omit<Document,"revision">={...current,...patch,labels:patch.labels?strings(patch.labels):current.labels,assignees:patch.assignees?strings(patch.assignees):current.assignees,blockedBy:patch.blockedBy?ids(patch.blockedBy):current.blockedBy,blocks:patch.blocks?ids(patch.blocks):current.blocks,related:patch.related?ids(patch.related):current.related,relationships,body:patch.body??current.body,preservedBody:current.preservedBody,updatedAt:now,...(patch.state==="finished"&&!current.finishedAt?{finishedAt:now}:{})};await this.#validate({...document,revision:current.revision});await atomicWrite(path.join(this.root,newName),encode(document));if(oldName!==newName)await rm(path.join(this.root,oldName),{force:true});index.files[id]=newName;await atomicWrite(path.join(this.root,".mpx-index.json"),JSON.stringify(index));return this.#changed(await this.view(id));});}
  async setDependency(id:string,dependencyId:string,present:boolean,expectedRevision?:string):Promise<LocalIssue>{if(id===dependencyId)throw new LocalIssueError("LOCAL_ISSUE_DEPENDENCY_INVALID","An issue cannot directly depend on itself.");return this.#locked(async()=>{const current=await this.#read(id),dependency=await this.#read(dependencyId);if(expectedRevision&&current.revision!==expectedRevision)throw new LocalIssueError("LOCAL_ISSUE_CONFLICT","The local issue changed since it was read.");const now=new Date().toISOString(),blockedBy=present?[...new Set([...current.blockedBy,dependencyId])].sort((a,b)=>Number(a)-Number(b)):current.blockedBy.filter(v=>v!==dependencyId),blocks=present?[...new Set([...dependency.blocks,id])].sort((a,b)=>Number(a)-Number(b)):dependency.blocks.filter(v=>v!==id);const index=await this.#index();await atomicWrite(path.join(this.root,index.files[id]!),encode({...current,blockedBy,updatedAt:now}));await atomicWrite(path.join(this.root,index.files[dependencyId]!),encode({...dependency,blocks,updatedAt:now}));return this.#changed(await this.view(id));});}
  async comment(id:string,body:string):Promise<IssueCommentV1>{return this.#locked(async()=>{const current=await this.#read(id),createdAt=new Date().toISOString(),commentId=`${id}-${Date.parse(createdAt)}`,index=await this.#index(),preserved=current.preservedBody||marker;await atomicWrite(path.join(this.root,index.files[id]!),encode({...current,preservedBody:preserved+`\n\n## Comment ${commentId}\n${body}`,updatedAt:createdAt}));await this.#changed(await this.view(id));return {schemaVersion:1,id:commentId,issueId:id,body,createdAt,providerData:{local:{nativeId:commentId}}};});}
  async promote(id:string,destination:string){if(!this.options.promotion)throw new ProviderError("CAPABILITY_UNSUPPORTED","Local issues have no configured board promotion adapter.",{capability:"issue.move"});const issue=await this.view(id),result=await this.options.promotion.promote(issue,destination);return result??issue;}
}

export function createLocalIssueAdapter(options:{root:string;staleLockMilliseconds?:number;promotion?:BoardPromotionAdapter;projectId?:string;onChanged?:(issue:LocalIssue)=>Promise<void>}):ProviderAdapter {const store=new LocalIssueStore(options.root,options),capabilities=[...ISSUE_CAPABILITIES,...LOCAL_ISSUE_CAPABILITIES];return {providerId:"local",role:"issues",backend:"filesystem",capabilities:capabilities as ProviderAdapter["capabilities"],routeRequired:false,async invoke(request:ProviderInvocation){const input=request.input as Record<string,unknown>;switch(request.capability){case"issue.list":return store.list(input.state as "open"|"finished"|undefined);case"issue.view":return store.view(String(input.id));case"issue.create":return store.create({title:String(input.title),body:String(input.body)});case"issue.edit":return store.update(String(input.id),{title:String(input.title),body:String(input.body)},typeof input.revision==="string"?input.revision:undefined);case"issue.comment":return store.comment(String(input.id),String(input.body));case"issue.label":{const issue=await store.view(String(input.id));return store.update(issue.id,{labels:[...issue.labels,String(input.label)]},String(issue.providerData.local.revision));}case"issue.finish":return store.update(String(input.id),{state:"finished",localState:"done"},typeof input.revision==="string"?input.revision:undefined);case"issue.move":return store.promote(String(input.id),String(input.destination));case"issue.dependency.add":return store.setDependency(String(input.id),String(input.dependencyId),true,typeof input.revision==="string"?input.revision:undefined);case"issue.dependency.remove":return store.setDependency(String(input.id),String(input.dependencyId),false,typeof input.revision==="string"?input.revision:undefined);default:throw new ProviderError("CAPABILITY_UNSUPPORTED",`Local issues do not support ${request.capability}.`,{capability:request.capability});}}};}

function validateOutput(vaultRoot:string,outputRoot:string){const vault=path.resolve(vaultRoot),output=path.resolve(outputRoot),relative=path.relative(vault,output);if(!path.isAbsolute(vaultRoot)||relative===""||relative===".."||relative.startsWith(`..${path.sep}`)||path.isAbsolute(relative)||!/^MPX(?:[\\/]|$)/u.test(relative))throw new LocalIssueError("LOCAL_VIEW_CONFIG_INVALID","Views require a configured MPX vault subtree.");return {vault,output};}
export interface ObsidianIssueViewConfig { vaultRoot:string;outputRoot:string;projectId:string;resumeBaseUrl:string }
export async function rebuildObsidianIssueViews(store:LocalIssueStore,config:ObsidianIssueViewConfig):Promise<{generated:number;removed:number}>{const {vault,output}=validateOutput(config.vaultRoot,config.outputRoot);if(!/^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/u.test(config.projectId)||!/^mpx:\/\/[A-Za-z0-9/?&=._%-]+$/u.test(config.resumeBaseUrl))throw new LocalIssueError("LOCAL_VIEW_CONFIG_INVALID","Obsidian issue views require safe metadata.");await assertNoSymlink(vault);await mkdir(output,{recursive:true});await assertNoSymlink(output);const issues=await store.list(),expected=new Set(issues.map(issue=>localIssueFilename(issue.id,issue.title)));let removed=0;for(const name of await readdir(output))if(filePattern.test(name)&&!expected.has(name)){await rm(path.join(output,name));removed++;}for(const issue of issues){const local=issue.providerData.local,deps=local.dependencies as unknown as LocalDependencies,url=`${config.resumeBaseUrl}${config.resumeBaseUrl.includes("?")?"&":"?"}project=${encodeURIComponent(config.projectId)}&issue=${issue.id}`,text=`---\nmpxGenerated: true\nproject: ${JSON.stringify(config.projectId)}\nissue: ${JSON.stringify(issue.id)}\nstate: ${JSON.stringify(issue.state)}\n---\n# ${issue.id}: ${issue.title}\n\n- State: ${issue.state}\n- Labels: ${issue.labels.join(", ")||"none"}\n- Dependency frontier: ${deps.frontier.join(", ")||"clear"}\n- [Resume](${url})\n`;await atomicWrite(path.join(output,localIssueFilename(issue.id,issue.title)),text);}return {generated:issues.length,removed};}
export interface PrivacySafeSessionView { id:string;projectId:string;status:string;title:string;resumeUrl:string;privateSummary?:string }
export interface ObsidianSessionViewConfig { vaultRoot:string;outputRoot:string }
export async function rebuildObsidianSessionViews(sessions:readonly PrivacySafeSessionView[],config:ObsidianSessionViewConfig):Promise<{generated:number;removed:number}>{const {vault,output}=validateOutput(config.vaultRoot,config.outputRoot),safe=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u;for(const session of sessions)if(!safe.test(session.id)||!safe.test(session.status)||!/^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/u.test(session.projectId)||session.title.length>256||!/^mpx:\/\/[A-Za-z0-9/?&=._%-]+$/u.test(session.resumeUrl))throw new LocalIssueError("LOCAL_VIEW_CONFIG_INVALID","Session view metadata or resume link is invalid.");await assertNoSymlink(vault);await mkdir(output,{recursive:true});await assertNoSymlink(output);const expected=new Set(sessions.map(s=>`${s.id}.md`));let removed=0;for(const name of await readdir(output))if(/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}\.md$/u.test(name)&&!expected.has(name)){await rm(path.join(output,name));removed++;}for(const session of sessions)await atomicWrite(path.join(output,`${session.id}.md`),`---\nmpxGenerated: true\nkind: session\nproject: ${JSON.stringify(session.projectId)}\nsession: ${JSON.stringify(session.id)}\nstatus: ${JSON.stringify(session.status)}\n---\n# ${session.title}\n\n- Status: ${session.status}\n- [Resume](${session.resumeUrl})\n`);return {generated:sessions.length,removed};}
