import { realpath } from "node:fs/promises"; import { resolve, sep } from "node:path"; import type { ExposureConfig, ProjectConfig, ProvenanceEntry, ResolvedConfig, UserConfig } from "./types.js"; import { sortProvenance } from "./provenance.js";
const win=process.platform==="win32";
function norm(p:string){let n=resolve(p).replace(/[\/]+$/g,"");return win?n.toLowerCase():n}
function contains(root:string,path:string){return path===root||path.startsWith(root+sep)||path.startsWith(root+(sep==="\\"?"/":"\\"))}
export async function classifyScope(cwd:string,user:UserConfig):Promise<{name:string;root?:string}>{const path=norm(await realpath(cwd));let best:{name:string;root:string}|undefined;for(const [name,s] of Object.entries(user.scopes))for(const raw of s.roots){let root:string;try{root=norm(await realpath(raw))}catch{root=norm(raw)}if(contains(root,path)&&(!best||root.length>best.root.length))best={name,root}}return best??{name:"core"}}
export async function resolveConfig(project:ProjectConfig,user:UserConfig,cwd:string):Promise<ResolvedConfig>{const found=await classifyScope(cwd,user);const scope=user.scopes[found.name];const override=user.projects?.[project.project.id];const provenance:ProvenanceEntry[]=[];const mark=(pointer:string,source:ProvenanceEntry["source"])=>provenance.push({pointer,source});
 const p:ProjectConfig=structuredClone(project);if(!p.issues){p.issues={provider:"none"};mark("/project/issues","default")}if(!p.tooling){p.tooling={packageManager:"auto"};mark("/project/tooling","default")}else if(!p.tooling.packageManager){p.tooling.packageManager="auto";mark("/project/tooling/packageManager","default")}
 const packs=override?.skillPacks??scope?.skillPacks??["core"];mark("/scope/skillPacks",override?.skillPacks?"user-project":scope?.skillPacks?"user-scope":"default");
 const exposure:ExposureConfig={default:override?.skillExposure?.default??scope?.skillExposure?.default??"name-only",skills:{...(scope?.skillExposure?.skills??{}),...(override?.skillExposure?.skills??{})}};mark("/scope/skillExposure/default",override?.skillExposure?.default?"user-project":scope?.skillExposure?.default?"user-scope":"default");
 const connections={...(scope?.connections??{}),...(override?.connections??{})};return {project:p,scope:{name:found.name,...(found.root?{root:found.root}:{}),skillPacks:[...packs],skillExposure:exposure,connections},provenance:sortProvenance(provenance)}}
