export type Harness = 'pi' | 'claude';
export type Account = 'personal' | 'work';
export type Exposure = 'normal' | 'name-only' | 'explicit-only';
export type ModelClass = 'mechanical' | 'exploration' | 'standard' | 'advanced' | 'frontier';
export type Thinking = 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max';
export type Capability = 'read' | 'search' | 'shell' | 'write' | 'browser' | 'context' | 'web';

/** Canonical metadata lives in frontmatter metadata.mpx, never in generated files. */
export interface SkillMetadata {
  schemaVersion: 1;
  skillPacks: string[];
  defaultExposure?: Exposure;
}
export interface AgentMetadata {
  schemaVersion: 1;
  modelClass: ModelClass;
  thinking: Thinking;
  capabilities: Capability[];
}
export interface RuntimeProfiles {
  schemaVersion: 1;
  models: Record<Harness, Record<ModelClass, string>>;
  tools: Record<Harness, Record<Capability, string[]>>;
}
/** Exact destination relative to package root; generated bytes only, no integrity authority. */
export interface Projection { path: string; content: Buffer }
export interface BuildResult { files: string[]; changed: string[] }

export interface RepositoryConfig {
  projectId: string;
  repository: { provider: 'github' | 'gitlab' | 'gerrit'; remote: string };
  issues: { provider: 'github' | 'kanbanflow'; metadata?: Record<string, unknown> };
  packageManager?: 'pnpm' | 'npm' | 'yarn' | 'bun';
  packs?: string[];
}
export interface UserConfig {
  accounts: Record<Account, Record<Harness, string>>;
  domains: Record<Account, string[]>;
  defaultPacks?: Partial<Record<Account, string[]>>;
  executables?: Partial<Record<Harness, string>>;
  piTitle?: { provider: string; model: string; thinking: Thinking };
}
export interface ProjectSelection {
  mainCheckout?: string;
  config?: RepositoryConfig;
  warnings: string[];
}
export interface PackSelection { packs: string[]; paths: string[]; warnings: string[] }
export interface LaunchSpec {
  executable: string;
  args: string[];
  cwd: string;
  env: NodeJS.ProcessEnv;
  label: string;
  warnings: string[];
  requiresConfirmation: boolean;
}
